config/routes.rb
Hydracamp::Application.routes.draw do
  Blacklight.add_routes(self)

  root :to => "catalog#index"

  devise_for :zombies

  resources :zombies do
    resources :tweets
  end
  
  resources :tweets
  
  root :to => "tweets#index"
  

end

app/models/solr_document.rb
# -*- encoding : utf-8 -*-
class SolrDocument 

  include Blacklight::Solr::Document
  
  # The following shows how to setup this blacklight document to display marc documents
  extension_parameters[:marc_source_field] = :marc_display
  extension_parameters[:marc_format_type] = :marcxml
  use_extension( Blacklight::Solr::Document::Marc) do |document|
    document.key?( :marc_display  )
  end
  
  # Email uses the semantic field mappings below to generate the body of an email.
  SolrDocument.use_extension( Blacklight::Solr::Document::Email )
  
  # SMS uses the semantic field mappings below to generate the body of an SMS email.
  SolrDocument.use_extension( Blacklight::Solr::Document::Sms )

  # DublinCore uses the semantic field mappings below to assemble an OAI-compliant Dublin Core document
  # Semantic mappings of solr stored fields. Fields may be multi or
  # single valued. See Blacklight::Solr::Document::ExtendableClassMethods#field_semantics
  # and Blacklight::Solr::Document#to_semantic_values
  # Recommendation: Use field names from Dublin Core
  use_extension( Blacklight::Solr::Document::DublinCore)    
  field_semantics.merge!(    
                         :title => "title_display",
                         :author => "author_display",
                         :language => "language_facet",
                         :format => "format"
                         )
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :zombie

  scope :ordered_chronologically, order('created_at desc')
  scope :ordered_by_zombie_name, joins(:zombie).order('zombies.name')
end

app/models/undead.rb
class Undead < ActiveFedora::Base
  has_metadata :name => "descMetadata", :type => ZombieEaccpfDatastream
end

app/models/zombie.rb
##TODO Zombie class should become Researcher (or User)
class Zombie < ActiveRecord::Base
# Connects this user object to Blacklights Bookmarks and Folders. 
 include Blacklight::User
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :graveyard, :name
  has_many :tweets
end

app/models/zombie_datastream.rb
class ZombieDatastream < ActiveFedora::NokogiriDatastream
  set_terminology do |t|
    t.root :xmlns=>'http://mediashelf.com/zombies', :path=>'zombie'
    t.body {
      t.name
      t.date_of_birth(:path=>'date', :attributes=>{'type'=>'birth'})
      t.date_of_undeath(:path=>'date', :attributes=>{'type'=>'undeath'})
      t.people(:path=>'peopleEaten') {
        t.name
      } 
    }
    t.people_eaten(:proxy=>[:body,:people, :name])
    t.date_of_birth(:proxy=>[:body, :date_of_birth])
    
  end
end

app/models/zombie_eaccpf_datastream.rb
class ZombieEaccpfDatastream < ActiveFedora::NokogiriDatastream

  set_terminology do |t|
    t.root(:path=>'eac-cpf', :xmlns=>'urn:isbn:1-931666-33-4')
    t.cpf_description(:path=>'cpfDescription') {
      t.identity {
        t.name_entry(:path=>'nameEntry') {
          t.part
          t.first_name(:ref=>[:cpf_description, :identity, :name_entry, :part], :attributes=>{'localType'=>'forename'},:index_as=>[:searchable, :facetable])
          t.last_name(:ref=>[:cpf_description, :identity, :name_entry, :part], :attributes=>{'localType'=>'surname'},:index_as=>[:searchable, :facetable])
        }
      }
      t.description {
        t.biog_hist(:path=>'biogHist') {
          t.chron_list(:path=>'chronList') {
            t.chron_item(:path=>'chronItem') {
              t.date
            }
            t.undeath_chron_item(:path=>"chronItem[oxns:event/text()='died']") {
              t.date_undeath(:path=>'date',:index_as=>[:searchable, :facetable])
            }
            t.born_chron_item(:path=>"chronItem[oxns:event/text()='Born']") {
              t.date_born(:path=>'date',:index_as=>[:searchable, :facetable])
            }
          }
        }
      }
    }
    t.date_undeath(:proxy=>[:cpf_description, :description, :biog_hist, :chron_list, :undeath_chron_item, :date_undeath ])
    t.date_of_birth(:proxy=>[:cpf_description, :description, :biog_hist, :chron_list, :born_chron_item, :date_born ])
    t.first_name(:proxy=>[:cpf_description, :identity, :name_entry, :first_name])
  end
  
  def self.xml_template
    Nokogiri::XML::Document.parse('<?xml version="1.0" encoding="UTF-8"?>
<eac-cpf xmlns="urn:isbn:1-931666-33-4"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="urn:isbn:1-931666-33-4 http://eac.staatsbibliothek-berlin.de/schema/cpf.xsd">
    <control>
   	 <recordId>P004686</recordId>
   	 <maintenanceStatus>new</maintenanceStatus>
   	 <maintenanceAgency>
   		 <agencyCode>AU-BS</agencyCode>
   		 <agencyName>Bright Sparcs</agencyName>
   	 </maintenanceAgency>
   	 <maintenanceHistory>
   		 <maintenanceEvent>
   			 <eventType>created</eventType>
   			 <eventDateTime>2006-03-28</eventDateTime>
   			 <agentType>human</agentType>
   			 <agent>Helen Hamilton for ANMHP</agent>
   			 <eventDescription>Record Created</eventDescription>
   		 </maintenanceEvent>
   	 </maintenanceHistory>
   	 <sources>
   		 <source xlink:href="http://nla.gov.au/anbd.aut-an35803761" xlink:type="simple">
   		 </source>
   	 </sources>
    </control>
    <cpfDescription>
   	 <identity>
   		 <entityId>P004686</entityId>
   		 <entityType>person</entityType>
   		 <nameEntry xml:lang="eng" scriptCode="Latn">
   			 <part localType="surname"></part>

   			 <part localType="forename"></part>
   			 <authorizedForm>AARC2</authorizedForm>
   		 </nameEntry>
   	 </identity>
   	 <description>
   		 <occupation>
   			 <term></term>
   		 </occupation>
   		 <biogHist>
   			 <p>foo</p>
   			 <chronList>
   				 <chronItem>
   					 <date></date>
   					 <event>Born</event>
   				 </chronItem>
   				 <chronItem>
   					 <date></date>
   					 <event>died</event>
   				 </chronItem>
   			 </chronList>
   		 </biogHist>
   	 </description>
    </cpfDescription>
</eac-cpf>
    ')
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Adds a few additional behaviors into the application controller 
   include Blacklight::Controller
  # Please be sure to impelement current_user and user_session. Blacklight depends on 
  # these methods in order to perform user specific actions. 

  protect_from_forgery
  
  def current_user
    return current_zombie
  end
  
end

app/controllers/catalog_controller.rb
# -*- encoding : utf-8 -*-
require 'blacklight/catalog'

class CatalogController < ApplicationController  

  include Blacklight::Catalog
  
end 

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  def index
    if params[:sort] == 'zombie'
      @tweets = Tweet.ordered_by_zombie_name
    else
      @tweets = Tweet.ordered_chronologically
    end

    @tweets = @tweets.page(params[:page]).per(10)
    @tweet = Tweet.new()
  end
  
  def new
    @zombie = Zombie.find(params[:zombie_id])
    @tweet = Tweet.new()
  end
  
  def create    
    @tweet = Tweet.new(params[:tweet])    
    @tweet.zombie = Zombie.find(params[:zombie_id])
    
    if @tweet.save
      flash[:notice] = "Created tweet."
    else
      flash[:error] = "Failed to create your tweet!"
    end
    redirect_to tweets_path
  end
  
end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController 
  def index 
    @zombies = Zombie.all
    
  end
  
  def show
    @zombie = Zombie.find(params[:id])
    
    respond_to do |format|
      format.html 
      format.xml { render :xml => @zombie.to_xml }
      format.json { render :json => @zombie.to_json }
    end
  end
  
  def edit
    @zombie = Zombie.find(params[:id])
  end
  
  def new
    @zombie = Zombie.new
  end
  
  def create
    @zombie = Zombie.new(params[:zombie])
    if @zombie.save
      flash[:notice] = "Created #{@zombie.name}"
    else
      flash[:error] = "Failed to create your zombie!"
    end
    redirect_to zombie_path(@zombie)
  end
  
  def update
    @zombie = Zombie.find(params[:id])
    @zombie.update_attributes(params[:zombie])
    if @zombie.save
      flash[:notice] = "Saved changes to #{@zombie.name}"
    else
      flash[:error] = "Failed to save your changes!"
    end
    redirect_to edit_zombie_path(@zombie)
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hydracamp</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>



<div class="content clearfix">
  <% if flash[:notice] %>
    <div class="notice">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <% if flash[:error] %>
    <div class="error">
      <%= flash[:error] %>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class="alert">
      <%= flash[:alert] %>
    </div>
  <% end %>
</div>

<div class="user_actions">
  <% if current_zombie.nil? %>
    <%= link_to "log in", new_zombie_session_path%>
  <% else %>
    Welcome <%= current_zombie.name %>
    <%= link_to "edit account", edit_zombie_registration_path%>
    <%= link_to "log out", destroy_zombie_session_path, :method=>:delete %>
    <%= link_to "Home", root_path %>
  <% end %>
</div>
<%= yield %>

</body>
</html>

app/views/tweets/_new.html.erb
<%= form_for [current_zombie, @tweet] do |f| %>
  <%= f.label :status %>
  <%= f.text_field :status %>
  <%= f.submit "Tweet" %>
<% end %>

app/views/tweets/index.html.erb
<h1>Tweets</h1>

<% if current_zombie != @zombie %>
  <%= render :partial => "new" %>
<% end %>

<h2>Everyone's Tweets</h2>

<%= paginate @tweets %>
<ul>
  <% @tweets.each do |tweet|%>
    <li>
      <%= link_to tweet.zombie.name, zombie_path(tweet.zombie) %>
      <%= tweet.status%> -
      <%= tweet.created_at.strftime("%I:%M %p %m/%d/%Y") %>


      
      <span class="zombie_graveyard_label">
      of <%= tweet.zombie.graveyard %>
      </span>
      
      
      
    </li>
  <% end%>  
</ul>
<%= paginate @tweets %>
<%= link_to "See all Zombies", zombies_path %>

app/views/tweets/new.html.erb
<h1>What's your Status?</h1>

<%= render :partial=>"new" %>

app/views/zombies/edit.html.erb
<h1>Name:<%=@zombie.name%></h1>
<div id="page_actions">
  <%= link_to "browse", zombie_path(@zombie) %> | edit
</div>

<%= form_for @zombie do |f| %>
  <dl>
    <dt class="name">
      <%= f.label "Name:" %>
    </dt>
    <dd class="name">
      <%= f.text_field :name %>
    </dd>
    <dt class="graveyard">
      <%= f.label "Graveyard:" %>
    </dt>
    <dd class="graveyard">
      <%= f.text_field :graveyard %>
    </dd>
  </dl>
  <%= f.submit "Save Changes" %>
<% end %>
<h2>Tweets:</h2>
<ul>
<% @zombie.tweets.each do |tweet|%>
<li><%= tweet.status %></li>
<% end %>
</ul>

app/views/zombies/edit.html.haml
%h1 
  Name:
  =@zombie.name
#page_actions
  browse | 
  = link_to "edit", edit_zombie_path(@zombie)
%dl
  %dt.name Name:
  %dd.name= @zombie.name
  %dt.graveyard 
    Graveyard:
  %dd.graveyard
    = @zombie.graveyard 
%h2 Tweets:
%ul
  - @zombie.tweets.each do |tweet|
    %li= tweet.status 

app/views/zombies/index.html.erb
<h1>Zombies</h1>
<ul>
<% @zombies.each do |zombie|%>
<li>
<%= link_to zombie.name, zombie %>
</li>
<% end%>  
</ul>

app/views/zombies/new.html.erb
<h1>Create a Zombie</h1>

<%= form_for @zombie do |f| %>
  <dl>
    <dt class="name">
      <%= f.label "Name:" %>
    </dt>
    <dd class="name">
      <%= f.text_field :name %>
    </dd>
    <dt class="graveyard">
      <%= f.label "Graveyard:" %>
    </dt>
    <dd class="graveyard">
      <%= f.text_field :graveyard %>
    </dd>
  </dl>
  <%= f.submit "Create Zombie" %>
<% end %>

app/views/zombies/show.html.erb
<h1>Name:<%=@zombie.name%></h1>
<div id="page_actions">
  <% if current_zombie == @zombie %>
    browse | <%= link_to "edit", edit_zombie_path(@zombie) %>
  <% end %>
</div>
<dl>
  <dt class="name">Name:</dt>
  <dd class="name"><%= @zombie.name %></dd>
  <dt class="graveyard">Graveyard:</dt>
  <dd class="graveyard"><%= @zombie.graveyard %></dd>
</dl>
<h2>Tweets:</h2>
<ul>
<% @zombie.tweets.each do |tweet|%>
<li><%= tweet.status %></li>
<% end %>
</ul>